version: "3.9"

# services:
#   db:
#     image: postgres:13.2-alpine
#     container_name: postgres_container
#     restart: always
#     environment:
#       POSTGRES_USER: admin
#       POSTGRES_PASSWORD: secret
#       POSTGRES_DB: mydatabase
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data:

services: 
  # backend_service: 
  #   build: .
  #   container_name: backend_container
  #   restart: always
  #   ports:
  #     - "8000:8000"
  #   env_file:
  #     - .env
  #   depends_on: 
  #     - redis_service
  #   networks: 
  #     - backend_network
  redis_service:
    image: "redis:alpine"
    container_name: redis_container
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    # networks:
    #   - backend_network
volumes:
  redis_data:

# networks: 
#   backend_network:
#     driver: bridge